services:
  mysql:
    image: mysql:8.0
    container_name: commitmood-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./docs/db:/docker-entrypoint-initdb.d:ro # sql 스키마 연결 위해 설정함.
    networks:
      - commitmood-net

  api:
    image: 904923506932.dkr.ecr.ap-northeast-2.amazonaws.com/commitmood-api:latest
    container_name: commitmood-api
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "443:8080"
      - "80:8080"
    networks:
      - commitmood-net

volumes:
  mysql-data:
    external: true

networks:
  commitmood-net: