spring:
  profiles:
    include: batch-secret
  sql:
    init:
      mode: never

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-prod-host:3306/commitmooddb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.commitmood.domain
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

logging:
  level:
    com.commitmood: INFO
    org.springframework: WARN